apiVersion: v1
kind: Service
metadata:
  name: boldog-web
spec:
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: boldog-web
  sessionAffinity: None
