apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: boldog
secretGenerator:
- name: mysql-pass
  literals:
  - password=password
resources:
- namespace.yaml
- mysql-deployment.yaml
- wordpress-deployment.yaml