apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: boldog

bases:
  - ../../base

resources:

patchesStrategicMerge:
  - boldog-web/hpa_replicas.yaml
  - boldog-web/ingress.yaml
  - boldog-web/deployment_resources.yaml

#configMapGenerator:
#  - name: boldog-web-config
#    env: boldog-web/config.env

images:
  - name: boldog-web
    newName: fr0z3nk0/boldogweb
    newTag: latest
