name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Auto-release')"

    steps:
      - uses: actions/checkout@v1
      - run: docker build -t fr0z3nk0/boldogweb:latest -t fr0z3nk0/boldogweb:$GITHUB_SHA .
      - run: docker build -f Dockerfile.db -t fr0z3nk0/boldogdb:latest -t fr0z3nk0/boldogdb:$GITHUB_SHA .
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push fr0z3nk0/boldogweb
      - run: docker push fr0z3nk0/boldogdb
