name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Auto-release')"

    steps:
      - uses: actions/checkout@v1
      - run: docker build -t fr0z3nk0/boldog-web:latest -t fr0z3nk0/boldog-web:$GITHUB_SHA .
      - run: docker build -f Dockerfile.db -t fr0z3nk0/boldog-db:latest -t fr0z3nk0/boldog-db:$GITHUB_SHA .
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push fr0z3nk0/boldog-web
      - run: docker push fr0z3nk0/boldog-db
